apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}-svc
spec:
  selector:
    app: {{ include "api.name" . }}
    color: {{ .Values.color }}   # 🔹 switch this to route traffic
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}