apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploycraft
spec:
  selector:
    matchLabels:
      app: deploycraft
  template:
    metadata:
      labels:
        app: deploycraft
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: deploycraft
          image: ghcr.io/augustus281/deploycraft:v1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: APP_VERSION
              value: "v1.0.0"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0