apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployscraft
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployscraft
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deployscraft
    spec:
      containers:
        - name: deployscraft
          image: ghcr.io/augustus281/deployscraft:latest
          ports:
            - containerPort: 8080